services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - API_URL=http://api:3001
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
            - .next/
    command: bun run --filter web dev
    networks:
      - fitness_net
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/fitnessdata
      - NODE_ENV=development
      - PORT=3001
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
    command: bun run --filter api dev
    networks:
      - fitness_net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fitnessdata
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d fitnessdata']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fitness_net
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  fitness_net:
    driver: bridge

volumes:
  postgres_data:
