import { OpenAPIHono, createRoute, z } from '@hono/zod-openapi';
import { db } from '@repo/db';
import { apiKeysTable } from '@repo/db/src/schema';
import { eq, desc } from 'drizzle-orm';
import { generateApiKey } from '../../lib/api-key';
import { env } from '../../lib/env';
import { UnauthorizedError, NotFoundError } from '../../lib/error';
import type { Context, Next } from 'hono';

// ─── Admin auth ────────────────────────────────────────────────────────────────
// Admin endpoints are protected by the MASTER_KEY env var (auto-generated by setup).
// Pass it via "Authorization: Bearer <master-key>" header.

async function requireAdmin(c: Context, next: Next) {
  const masterKey = env.MASTER_KEY;

  const authHeader = c.req.header('authorization');
  const provided = authHeader?.replace(/^Bearer\s+/i, '');
  if (!provided || provided !== masterKey) {
    throw new UnauthorizedError('Invalid master key.');
  }

  await next();
}

// ─── Schemas ───────────────────────────────────────────────────────────────────

const apiKeyResponseSchema = z.object({
  id: z.number(),
  keyPrefix: z.string(),
  name: z.string(),
  owner: z.string(),
  scopes: z.array(z.string()).nullable(),
  rateLimitMax: z.number().nullable(),
  rateLimitWindowSecs: z.number().nullable(),
  requestCount: z.number(),
  lastUsedAt: z.string().datetime().nullable(),
  expiresAt: z.string().datetime().nullable(),
  revoked: z.boolean(),
  revokedAt: z.string().datetime().nullable(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

const createApiKeyBodySchema = z.object({
  name: z
    .string()
    .min(1)
    .max(256)
    .openapi({ description: 'Human-readable label for the key' }),
  owner: z
    .string()
    .min(1)
    .max(256)
    .openapi({ description: 'Owner identifier (email, user ID, org name)' }),
  scopes: z
    .array(z.string())
    .optional()
    .openapi({ description: 'Allowed scopes. Omit for full access.' }),
  rateLimitMax: z
    .number()
    .int()
    .positive()
    .optional()
    .openapi({ description: 'Max requests per rate limit window' }),
  rateLimitWindowSecs: z
    .number()
    .int()
    .positive()
    .optional()
    .openapi({ description: 'Rate limit window in seconds' }),
  expiresInDays: z
    .number()
    .int()
    .positive()
    .optional()
    .openapi({
      description:
        'Number of days until the key expires. Omit for no expiration.',
    }),
});

// ─── Routes ────────────────────────────────────────────────────────────────────

const admin = new OpenAPIHono();

// Apply admin auth to all routes in this router
admin.use('*', requireAdmin);

// --- Create API key ---

const createApiKeyRoute = createRoute({
  method: 'post',
  path: '/',
  tags: ['Admin – API Keys'],
  summary: 'Create a new API key',
  description:
    'Generate a new API key. The plaintext key is returned ONLY in this response and is never stored.',
  request: {
    body: {
      content: {
        'application/json': {
          schema: createApiKeyBodySchema,
        },
      },
    },
  },
  responses: {
    201: {
      description: 'API key created',
      content: {
        'application/json': {
          schema: z.object({
            success: z.boolean(),
            /** The plaintext key – shown only once! */
            key: z.string(),
            apiKey: apiKeyResponseSchema,
          }),
        },
      },
    },
  },
});

admin.openapi(createApiKeyRoute, async (c) => {
  const body = c.req.valid('json');

  const { plaintextKey, keyPrefix, keyHash } = generateApiKey();

  const expiresAt = body.expiresInDays
    ? new Date(Date.now() + body.expiresInDays * 86_400_000)
    : null;

  const [inserted] = await db
    .insert(apiKeysTable)
    .values({
      keyPrefix,
      keyHash,
      name: body.name,
      owner: body.owner,
      scopes: body.scopes ?? null,
      rateLimitMax: body.rateLimitMax ?? null,
      rateLimitWindowSecs: body.rateLimitWindowSecs ?? null,
      expiresAt,
    })
    .returning();

  return c.json(
    {
      success: true,
      key: plaintextKey,
      apiKey: formatKeyRecord(inserted!),
    },
    201,
  );
});

// --- List API keys ---

const listApiKeysRoute = createRoute({
  method: 'get',
  path: '/',
  tags: ['Admin – API Keys'],
  summary: 'List all API keys',
  description: 'List all API keys with their metadata (hashes are never returned).',
  request: {
    query: z.object({
      limit: z.string().default('50').transform(Number),
      offset: z.string().default('0').transform(Number),
      owner: z.string().optional(),
    }),
  },
  responses: {
    200: {
      description: 'List of API keys',
      content: {
        'application/json': {
          schema: z.object({
            success: z.boolean(),
            keys: z.array(apiKeyResponseSchema),
          }),
        },
      },
    },
  },
});

admin.openapi(listApiKeysRoute, async (c) => {
  const { limit, offset, owner } = c.req.valid('query');

  let query = db
    .select()
    .from(apiKeysTable)
    .orderBy(desc(apiKeysTable.createdAt))
    .limit(limit)
    .offset(offset);

  if (owner) {
    query = query.where(eq(apiKeysTable.owner, owner)) as typeof query;
  }

  const keys = await query;

  return c.json({
    success: true,
    keys: keys.map(formatKeyRecord),
  });
});

// --- Get single API key ---

const getApiKeyRoute = createRoute({
  method: 'get',
  path: '/{id}',
  tags: ['Admin – API Keys'],
  summary: 'Get an API key by ID',
  request: {
    params: z.object({ id: z.string().transform(Number) }),
  },
  responses: {
    200: {
      description: 'API key details',
      content: {
        'application/json': {
          schema: z.object({
            success: z.boolean(),
            apiKey: apiKeyResponseSchema,
          }),
        },
      },
    },
    404: { description: 'API key not found' },
  },
});

admin.openapi(getApiKeyRoute, async (c) => {
  const { id } = c.req.valid('param');
  const [key] = await db
    .select()
    .from(apiKeysTable)
    .where(eq(apiKeysTable.id, id))
    .limit(1);

  if (!key) throw new NotFoundError('API Key');

  return c.json({ success: true, apiKey: formatKeyRecord(key) });
});

// --- Revoke API key ---

const revokeApiKeyRoute = createRoute({
  method: 'post',
  path: '/{id}/revoke',
  tags: ['Admin – API Keys'],
  summary: 'Revoke an API key',
  description: 'Immediately revoke an API key. This cannot be undone.',
  request: {
    params: z.object({ id: z.string().transform(Number) }),
  },
  responses: {
    200: {
      description: 'API key revoked',
      content: {
        'application/json': {
          schema: z.object({
            success: z.boolean(),
            apiKey: apiKeyResponseSchema,
          }),
        },
      },
    },
    404: { description: 'API key not found' },
  },
});

admin.openapi(revokeApiKeyRoute, async (c) => {
  const { id } = c.req.valid('param');
  const [key] = await db
    .update(apiKeysTable)
    .set({
      revoked: true,
      revokedAt: new Date(),
      updatedAt: new Date(),
    })
    .where(eq(apiKeysTable.id, id))
    .returning();

  if (!key) throw new NotFoundError('API Key');

  return c.json({ success: true, apiKey: formatKeyRecord(key) });
});

// --- Delete API key ---

const deleteApiKeyRoute = createRoute({
  method: 'delete',
  path: '/{id}',
  tags: ['Admin – API Keys'],
  summary: 'Permanently delete an API key',
  request: {
    params: z.object({ id: z.string().transform(Number) }),
  },
  responses: {
    200: {
      description: 'API key deleted',
      content: {
        'application/json': {
          schema: z.object({ success: z.boolean(), message: z.string() }),
        },
      },
    },
    404: { description: 'API key not found' },
  },
});

admin.openapi(deleteApiKeyRoute, async (c) => {
  const { id } = c.req.valid('param');
  const [deleted] = await db
    .delete(apiKeysTable)
    .where(eq(apiKeysTable.id, id))
    .returning();

  if (!deleted) throw new NotFoundError('API Key');

  return c.json({ success: true, message: `API key ${id} deleted.` });
});

// ─── Helpers ───────────────────────────────────────────────────────────────────

function formatKeyRecord(k: typeof apiKeysTable.$inferSelect) {
  return {
    id: k.id,
    keyPrefix: k.keyPrefix,
    name: k.name,
    owner: k.owner,
    scopes: k.scopes as string[] | null,
    rateLimitMax: k.rateLimitMax,
    rateLimitWindowSecs: k.rateLimitWindowSecs,
    requestCount: k.requestCount,
    lastUsedAt: k.lastUsedAt?.toISOString() ?? null,
    expiresAt: k.expiresAt?.toISOString() ?? null,
    revoked: k.revoked,
    revokedAt: k.revokedAt?.toISOString() ?? null,
    createdAt: k.createdAt.toISOString(),
    updatedAt: k.updatedAt.toISOString(),
  };
}

export default admin;
